# Generated by Django 3.0 on 2021-03-02 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
