# Generated by Django 3.0 on 2021-03-02 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210302_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='title',
            options={},
        ),
    ]
